require 'rspec/core/rake_task'
RSpec::Core::RakeTask.new(:test, :test_name) do |t, j|
	pattern = j[:test_name] ? j[:test_name] : "*"
	t.pattern = "specs/#{pattern}.rb"
	t.rspec_opts = '--color --format s'
end