require 'rb_shark'
require_relative './conversion_text/conversion_text.rb'
require_relative './autoencoder_text/autoencoder_text.rb'
require_relative './pca_text/pca_text.rb'
require_relative './binaryrbm_text/binaryrbm_text.rb'
require_relative './deep_belief_network/deep_belief_network.rb'
require_relative './datatypes/datatypes.rb'